# 服务信息配置
server:
  port: 8081

# 数据库连接
# serverTimezone=GMT%2B8 同步北京时间
spring:
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/goamall?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: urun1234
  jpa:
    properties:
      hibernate:
        # 显示SQL查询语句
        show_sql: true
        format_sql: true
nuon:
  security:
    # token令牌key
    jwt-key: nuon20190802
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600