spring:
  profiles:
    # resource下文件引用激活
    active: dev
  jpa:
    hibernate:
      # update 新增模型才更新表配置，create-drop 是清空后生成新的表，none 不生成
      ddl-auto: none
  jackson:
    # 属性值下划线拼接
    property-naming-strategy: SNAKE_CASE
    serialization:
      # 日期时间设定为时间戳格式
      WRITE_DATES_AS_TIMESTAMPS: true

# 定义接口所在路径
goamall:
  api-package: com.nuon.goamall.api

wx:
  appid: wx376e1a77e4c7ffa4
  appsecret: 3eab8e1112ef6549560684e1362cef1e
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code

